/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppAdminInvitesRouteImport } from './routes/_app.admin.invites'
import { Route as AppNotesIndexRouteImport } from './routes/_app.notes.index'
import { Route as AppNotesNoteIdRouteImport } from './routes/_app.notes.$noteId'
import { Route as AppPlantsIndexRouteImport } from './routes/_app.plants.index'
import { Route as AppPlantsPlantIdRouteImport } from './routes/_app.plants.$plantId'
import { Route as AppPlantsCalendarRouteImport } from './routes/_app.plants.calendar'
import { Route as AppPlantsNewRouteImport } from './routes/_app.plants.new'
import { Route as AppSettingsIndexRouteImport } from './routes/_app.settings.index'
import { Route as AppSettingsDomainRouteImport } from './routes/_app.settings.$domain'
import { Route as AppSettingsAccountRouteImport } from './routes/_app.settings.account'
import { Route as AppSettingsTokensRouteImport } from './routes/_app.settings.tokens'
import { Route as AppPlantsPlantIdEditRouteImport } from './routes/_app.plants.$plantId.edit'

const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminInvitesRoute = AppAdminInvitesRouteImport.update({
  id: '/admin/invites',
  path: '/admin/invites',
  getParentRoute: () => AppRoute,
} as any)
const AppNotesIndexRoute = AppNotesIndexRouteImport.update({
  id: '/notes/',
  path: '/notes/',
  getParentRoute: () => AppRoute,
} as any)
const AppNotesNoteIdRoute = AppNotesNoteIdRouteImport.update({
  id: '/notes/$noteId',
  path: '/notes/$noteId',
  getParentRoute: () => AppRoute,
} as any)
const AppPlantsIndexRoute = AppPlantsIndexRouteImport.update({
  id: '/plants/',
  path: '/plants/',
  getParentRoute: () => AppRoute,
} as any)
const AppPlantsPlantIdRoute = AppPlantsPlantIdRouteImport.update({
  id: '/plants/$plantId',
  path: '/plants/$plantId',
  getParentRoute: () => AppRoute,
} as any)
const AppPlantsCalendarRoute = AppPlantsCalendarRouteImport.update({
  id: '/plants/calendar',
  path: '/plants/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppPlantsNewRoute = AppPlantsNewRouteImport.update({
  id: '/plants/new',
  path: '/plants/new',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsDomainRoute = AppSettingsDomainRouteImport.update({
  id: '/settings/$domain',
  path: '/settings/$domain',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsAccountRoute = AppSettingsAccountRouteImport.update({
  id: '/settings/account',
  path: '/settings/account',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsTokensRoute = AppSettingsTokensRouteImport.update({
  id: '/settings/tokens',
  path: '/settings/tokens',
  getParentRoute: () => AppRoute,
} as any)
const AppPlantsPlantIdEditRoute = AppPlantsPlantIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AppPlantsPlantIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/$': typeof SplatRoute
  '/': typeof AppIndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/login': typeof LoginRoute
  '/admin/invites': typeof AppAdminInvitesRoute
  '/notes/$noteId': typeof AppNotesNoteIdRoute
  '/plants/$plantId': typeof AppPlantsPlantIdRouteWithChildren
  '/plants/calendar': typeof AppPlantsCalendarRoute
  '/plants/new': typeof AppPlantsNewRoute
  '/settings/$domain': typeof AppSettingsDomainRoute
  '/settings/account': typeof AppSettingsAccountRoute
  '/settings/tokens': typeof AppSettingsTokensRoute
  '/notes/': typeof AppNotesIndexRoute
  '/plants/': typeof AppPlantsIndexRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/plants/$plantId/edit': typeof AppPlantsPlantIdEditRoute
}
export interface FileRoutesByTo {
  '/$': typeof SplatRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/login': typeof LoginRoute
  '/': typeof AppIndexRoute
  '/admin/invites': typeof AppAdminInvitesRoute
  '/notes/$noteId': typeof AppNotesNoteIdRoute
  '/plants/$plantId': typeof AppPlantsPlantIdRouteWithChildren
  '/plants/calendar': typeof AppPlantsCalendarRoute
  '/plants/new': typeof AppPlantsNewRoute
  '/settings/$domain': typeof AppSettingsDomainRoute
  '/settings/account': typeof AppSettingsAccountRoute
  '/settings/tokens': typeof AppSettingsTokensRoute
  '/notes': typeof AppNotesIndexRoute
  '/plants': typeof AppPlantsIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/plants/$plantId/edit': typeof AppPlantsPlantIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$': typeof SplatRoute
  '/_app': typeof AppRouteWithChildren
  '/accept-invite': typeof AcceptInviteRoute
  '/login': typeof LoginRoute
  '/_app/': typeof AppIndexRoute
  '/_app/admin/invites': typeof AppAdminInvitesRoute
  '/_app/notes/$noteId': typeof AppNotesNoteIdRoute
  '/_app/plants/$plantId': typeof AppPlantsPlantIdRouteWithChildren
  '/_app/plants/calendar': typeof AppPlantsCalendarRoute
  '/_app/plants/new': typeof AppPlantsNewRoute
  '/_app/settings/$domain': typeof AppSettingsDomainRoute
  '/_app/settings/account': typeof AppSettingsAccountRoute
  '/_app/settings/tokens': typeof AppSettingsTokensRoute
  '/_app/notes/': typeof AppNotesIndexRoute
  '/_app/plants/': typeof AppPlantsIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/plants/$plantId/edit': typeof AppPlantsPlantIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$'
    | '/'
    | '/accept-invite'
    | '/login'
    | '/admin/invites'
    | '/notes/$noteId'
    | '/plants/$plantId'
    | '/plants/calendar'
    | '/plants/new'
    | '/settings/$domain'
    | '/settings/account'
    | '/settings/tokens'
    | '/notes/'
    | '/plants/'
    | '/settings/'
    | '/plants/$plantId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$'
    | '/accept-invite'
    | '/login'
    | '/'
    | '/admin/invites'
    | '/notes/$noteId'
    | '/plants/$plantId'
    | '/plants/calendar'
    | '/plants/new'
    | '/settings/$domain'
    | '/settings/account'
    | '/settings/tokens'
    | '/notes'
    | '/plants'
    | '/settings'
    | '/plants/$plantId/edit'
  id:
    | '__root__'
    | '/$'
    | '/_app'
    | '/accept-invite'
    | '/login'
    | '/_app/'
    | '/_app/admin/invites'
    | '/_app/notes/$noteId'
    | '/_app/plants/$plantId'
    | '/_app/plants/calendar'
    | '/_app/plants/new'
    | '/_app/settings/$domain'
    | '/_app/settings/account'
    | '/_app/settings/tokens'
    | '/_app/notes/'
    | '/_app/plants/'
    | '/_app/settings/'
    | '/_app/plants/$plantId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SplatRoute: typeof SplatRoute
  AppRoute: typeof AppRouteWithChildren
  AcceptInviteRoute: typeof AcceptInviteRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/invites': {
      id: '/_app/admin/invites'
      path: '/admin/invites'
      fullPath: '/admin/invites'
      preLoaderRoute: typeof AppAdminInvitesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notes/': {
      id: '/_app/notes/'
      path: '/notes'
      fullPath: '/notes/'
      preLoaderRoute: typeof AppNotesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notes/$noteId': {
      id: '/_app/notes/$noteId'
      path: '/notes/$noteId'
      fullPath: '/notes/$noteId'
      preLoaderRoute: typeof AppNotesNoteIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/plants/': {
      id: '/_app/plants/'
      path: '/plants'
      fullPath: '/plants/'
      preLoaderRoute: typeof AppPlantsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/plants/$plantId': {
      id: '/_app/plants/$plantId'
      path: '/plants/$plantId'
      fullPath: '/plants/$plantId'
      preLoaderRoute: typeof AppPlantsPlantIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/plants/calendar': {
      id: '/_app/plants/calendar'
      path: '/plants/calendar'
      fullPath: '/plants/calendar'
      preLoaderRoute: typeof AppPlantsCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/plants/new': {
      id: '/_app/plants/new'
      path: '/plants/new'
      fullPath: '/plants/new'
      preLoaderRoute: typeof AppPlantsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/$domain': {
      id: '/_app/settings/$domain'
      path: '/settings/$domain'
      fullPath: '/settings/$domain'
      preLoaderRoute: typeof AppSettingsDomainRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/account': {
      id: '/_app/settings/account'
      path: '/settings/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AppSettingsAccountRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/tokens': {
      id: '/_app/settings/tokens'
      path: '/settings/tokens'
      fullPath: '/settings/tokens'
      preLoaderRoute: typeof AppSettingsTokensRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/plants/$plantId/edit': {
      id: '/_app/plants/$plantId/edit'
      path: '/edit'
      fullPath: '/plants/$plantId/edit'
      preLoaderRoute: typeof AppPlantsPlantIdEditRouteImport
      parentRoute: typeof AppPlantsPlantIdRoute
    }
  }
}

interface AppPlantsPlantIdRouteChildren {
  AppPlantsPlantIdEditRoute: typeof AppPlantsPlantIdEditRoute
}

const AppPlantsPlantIdRouteChildren: AppPlantsPlantIdRouteChildren = {
  AppPlantsPlantIdEditRoute: AppPlantsPlantIdEditRoute,
}

const AppPlantsPlantIdRouteWithChildren =
  AppPlantsPlantIdRoute._addFileChildren(AppPlantsPlantIdRouteChildren)

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppAdminInvitesRoute: typeof AppAdminInvitesRoute
  AppNotesNoteIdRoute: typeof AppNotesNoteIdRoute
  AppPlantsPlantIdRoute: typeof AppPlantsPlantIdRouteWithChildren
  AppPlantsCalendarRoute: typeof AppPlantsCalendarRoute
  AppPlantsNewRoute: typeof AppPlantsNewRoute
  AppSettingsDomainRoute: typeof AppSettingsDomainRoute
  AppSettingsAccountRoute: typeof AppSettingsAccountRoute
  AppSettingsTokensRoute: typeof AppSettingsTokensRoute
  AppNotesIndexRoute: typeof AppNotesIndexRoute
  AppPlantsIndexRoute: typeof AppPlantsIndexRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppAdminInvitesRoute: AppAdminInvitesRoute,
  AppNotesNoteIdRoute: AppNotesNoteIdRoute,
  AppPlantsPlantIdRoute: AppPlantsPlantIdRouteWithChildren,
  AppPlantsCalendarRoute: AppPlantsCalendarRoute,
  AppPlantsNewRoute: AppPlantsNewRoute,
  AppSettingsDomainRoute: AppSettingsDomainRoute,
  AppSettingsAccountRoute: AppSettingsAccountRoute,
  AppSettingsTokensRoute: AppSettingsTokensRoute,
  AppNotesIndexRoute: AppNotesIndexRoute,
  AppPlantsIndexRoute: AppPlantsIndexRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SplatRoute: SplatRoute,
  AppRoute: AppRouteWithChildren,
  AcceptInviteRoute: AcceptInviteRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
