import js from '@eslint/js';
import jsxA11y from 'eslint-plugin-jsx-a11y';
import globals from 'globals';
import tseslint from 'typescript-eslint';

export default tseslint.config(
  {
    // src/api/generated is regenerated by `pnpm api:generate` (M02) and is
    // read-only from the implementer's side (WEB-SPEC §6.2); routeTree.gen.ts
    // is generated by TanStack Router (M04). TypeScript still type-checks
    // both — see tsconfig.json's `include`.
    ignores: ['dist', 'src/api/generated', 'src/routeTree.gen.ts', 'coverage', 'playwright-report'],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    files: ['src/**/*.{ts,tsx}', 'tests/**/*.{ts,tsx}', 'public/**/*.js'],
    languageOptions: {
      ecmaVersion: 2022,
      globals: globals.browser,
    },
  },
  {
    // Node-side tooling config files and build scripts run outside the browser.
    files: ['*.config.{ts,js}', 'scripts/**/*.mjs'],
    languageOptions: {
      globals: globals.node,
    },
  },
  {
    // lighthouserc.cjs and scripts/lighthouse-auth.cjs mix Node driver code
    // with browser code injected via Puppeteer's page.evaluate() in the
    // same file (a normal pattern for LHCI puppeteerScript hooks) — both
    // global sets apply.
    files: ['*.cjs', 'scripts/**/*.cjs'],
    languageOptions: {
      globals: { ...globals.node, ...globals.browser },
    },
  },
  {
    files: ['**/*.{jsx,tsx}'],
    ...jsxA11y.flatConfigs.recommended,
  },
);
